services:
    - type: web
      name: mental-health-api
      env: node
      plan: standard
      buildCommand: "npm install && npm run prisma-generate && npm run build"
      startCommand: "npm run prod"
      envVars:
          - key: NODE_ENV
            value: production
          - key: NODE_OPTIONS
            value: "--max-old-space-size=512"
      healthCheckPath: /api
