export const config = {
	ERROR: {
		USER: {
			NOT_FOUND: "User not found",
			INVALID_ID: "Invalid user ID",
			MISSING_ID: "Missing user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update user",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			INVALID_PHONE: "Invalid phone number format",
			PHONE_ALREADY_IN_USE: "Phone number already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
		},
		PERSON: {
			NOT_FOUND: "Person not found",
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update person",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			PHONE_ALREADY_IN_USE: "Contact number is already registered to a different person",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
		},
		STUDENT: {
			NOT_FOUND: "Student not found",
			INVALID_ID: "Invalid student ID",
			MISSING_ID: "Missing student ID",
			USER_ID_REQUIRED: "Student ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting student",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update student",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating student",
			ERROR_DELETING_USER: "Error deleting student",
			INVALID_USER_DATA: "Invalid user data provided for student",
			STUDENT_NUMBER_REQUIRED: "Student number is required",
			PROGRAM_REQUIRED: "Program is required",
			YEAR_REQUIRED: "Year is required",
			EXISTING_STUDENT: "Student already exists",
			STUDENT_NUMBER_EXISTS: "Student number already exists",
		},
		ANNOUNCEMENT: {
			NOT_FOUND: "Announcement not found",
			INVALID_ID: "Invalid announcement ID",
			MISSING_ID: "Missing announcement ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ANNOUNCEMENT: "Error getting announcement",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update announcement",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ANNOUNCEMENT: "Error updating announcement",
			ERROR_DELETING_ANNOUNCEMENT: "Error deleting announcement",
			INVALID_DATA: "Invalid announcement data provided",
			EXISTING_ANNOUNCEMENT: "Announcement already exists",
			INVALID_TITLE: "Invalid announcement title",
			TITLE_REQUIRED: "Announcement title is required",
			INVALID_DESCRIPTION: "Invalid announcement description",
			DESCRIPTION_REQUIRED: "Announcement description is required",
			INVALID_ATTACHEMENT: "Invalid attachment value",
		},
		LOGS: {
			NOT_FOUND: "Log not found",
			INVALID_ID: "Invalid log ID",
			MISSING_ID: "Missing log ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_LOG: "Error getting log",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update log",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_LOG: "Error updating log",
			ERROR_DELETING_LOG: "Error deleting log",
			INVALID_DATA: "Invalid log data provided",
			EXISTING_LOG: "Log already exists",
			INVALID_TYPE: "Invalid log type",
			TYPE_REQUIRED: "Log type is required",
			INVALID_ACTION: "Invalid log action",
			ACTION_REQUIRED: "Log action is required",
			INVALID_TITLE: "Invalid log title",
			TITLE_REQUIRED: "Log title is required",
			INVALID_STATUS: "Invalid log status",
			INVALID_SEVERITY: "Invalid log severity",
			USER_NOT_FOUND: "User not found for this log",
			INVALID_USER_ID: "Invalid user ID",
		},
	},

	SUCCESS: {
		USER: {
			RETRIEVED: "User retrieved",
			DELETED: "User deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "User updated",
			CREATED: "User created",
			LOGGED_IN: "User logged in",
			GETTING_USER_BY_ID: "Getting user by ID",
			GETTING_ALL_USERS: "Getting all users",
		},
		PERSON: {
			RETRIEVED: "Person retrieved",
			DELETED: "Person deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "Person updated",
			CREATED: "Person created",
			LOGGED_IN: "Person logged in",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		STUDENT: {
			RETRIEVED: "Student retrieved",
			DELETED: "Student deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "Student updated",
			CREATED: "Student created",
			LOGGED_IN: "Student logged in",
			GETTING_USER_BY_ID: "Getting student by ID",
			GETTING_ALL_USERS: "Getting all students",
		},
		ANNOUNCEMENT: {
			RETRIEVED: "Announcement retrieved",
			DELETED: "Announcement deleted",
			SOFT_DELETING: "Soft deleting announcement",
			UPDATE: "Announcement updated",
			CREATED: "Announcement created",
			GETTING_BY_ID: "Getting announcement by ID",
			GETTING_ALL: "Getting all announcements",
		},
		LOGS: {
			RETRIEVED: "Log retrieved",
			DELETED: "Log deleted",
			SOFT_DELETING: "Soft deleting log",
			UPDATE: "Log updated",
			CREATED: "Log created",
			GETTING_BY_ID: "Getting log by ID",
			GETTING_ALL: "Getting all logs",
			MARKED_AS_READ: "Log marked as read",
			MARKED_AS_UNREAD: "Log marked as unread",
		},
	},
};
