export const config = {
	ERROR: {
		USER: {
			NOT_FOUND: "User not found",
			INVALID_ID: "Invalid user ID",
			MISSING_ID: "Missing user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting user",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update user",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			INVALID_PHONE: "Invalid phone number format",
			PHONE_ALREADY_IN_USE: "Phone number already in use",
			ERROR_UPDATING_USER: "Error updating user",
			ERROR_DELETING_USER: "Error deleting user",
		},
		PERSON: {
			NOT_FOUND: "Person not found",
			INVALID_ID: "Invalid person ID",
			MISSING_ID: "Missing person ID",
			USER_ID_REQUIRED: "Person ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting person",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update person",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			PHONE_ALREADY_IN_USE: "Contact number is already registered to a different person",
			ERROR_UPDATING_USER: "Error updating person",
			ERROR_DELETING_USER: "Error deleting person",
		},
		STUDENT: {
			NOT_FOUND: "Student not found",
			INVALID_ID: "Invalid student ID",
			MISSING_ID: "Missing student ID",
			USER_ID_REQUIRED: "Student ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_USER: "Error getting student",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update student",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			INVALID_EMAIL: "Invalid email format",
			EMAIL_ALREADY_EXISTS: "Email already exists",
			EMAIL_ALREADY_IN_USED: "Email already in use",
			ERROR_UPDATING_USER: "Error updating student",
			ERROR_DELETING_USER: "Error deleting student",
			INVALID_USER_DATA: "Invalid user data provided for student",
			STUDENT_NUMBER_REQUIRED: "Student number is required",
			PROGRAM_REQUIRED: "Program is required",
			YEAR_REQUIRED: "Year is required",
			EXISTING_STUDENT: "Student already exists",
			STUDENT_NUMBER_EXISTS: "Student number already exists",
		},
		ANNOUNCEMENT: {
			NOT_FOUND: "Announcement not found",
			INVALID_ID: "Invalid announcement ID",
			MISSING_ID: "Missing announcement ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ANNOUNCEMENT: "Error getting announcement",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update announcement",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ANNOUNCEMENT: "Error updating announcement",
			ERROR_DELETING_ANNOUNCEMENT: "Error deleting announcement",
			INVALID_DATA: "Invalid announcement data provided",
			EXISTING_ANNOUNCEMENT: "Announcement already exists",
			INVALID_TITLE: "Invalid announcement title",
			TITLE_REQUIRED: "Announcement title is required",
			INVALID_DESCRIPTION: "Invalid announcement description",
			DESCRIPTION_REQUIRED: "Announcement description is required",
			INVALID_ATTACHEMENT: "Invalid attachment value",
		},
		CONSENT: {
			NOT_FOUND: "Consent not found",
			INVALID_ID: "Invalid consent ID",
			MISSING_ID: "Missing consent ID",
			STUDENT_ID_REQUIRED: "Student ID is required",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_CONSENT: "Error getting consent",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update consent",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_CONSENT: "Error updating consent",
			ERROR_DELETING_CONSENT: "Error deleting consent",
			INVALID_DATA: "Invalid consent data provided",
			EXISTING_CONSENT: "Consent already exists for this student",
			STUDENT_NOT_FOUND: "Student not found",
			INVALID_REFERRED: "Invalid referred value",
			INVALID_LIVE: "Invalid living situation value",
			INVALID_FINANCIAL: "Invalid financial status value",
			INVALID_PHYSICAL_PROBLEM: "Invalid physical problem value",
			INVALID_PHYSICAL_SYMPTOMS: "Invalid physical symptoms value",
			INVALID_SERVICES: "Invalid services value",
			INVALID_STRESS_LEVEL: "Invalid stress level value",
			INVALID_PERFORMANCE_CHANGE: "Invalid performance change value",
			INVALID_LEVEL_OF_IMPORTANCE: "Invalid level of importance value",
		},
		LOGS: {
			NOT_FOUND: "Log not found",
			INVALID_ID: "Invalid log ID",
			MISSING_ID: "Missing log ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_LOG: "Error getting log",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update log",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_LOG: "Error updating log",
			ERROR_DELETING_LOG: "Error deleting log",
			INVALID_DATA: "Invalid log data provided",
			EXISTING_LOG: "Log already exists",
			INVALID_TYPE: "Invalid log type",
			TYPE_REQUIRED: "Log type is required",
			INVALID_ACTION: "Invalid log action",
			ACTION_REQUIRED: "Log action is required",
			INVALID_TITLE: "Invalid log title",
			TITLE_REQUIRED: "Log title is required",
			INVALID_STATUS: "Invalid log status",
			INVALID_SEVERITY: "Invalid log severity",
			USER_NOT_FOUND: "User not found for this log",
			INVALID_USER_ID: "Invalid user ID",
		},
		ANXIETY: {
			NOT_FOUND: "Anxiety assessment not found",
			INVALID_ID: "Invalid anxiety assessment ID",
			MISSING_ID: "Missing anxiety assessment ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ASSESSMENT: "Error getting anxiety assessment",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update anxiety assessment",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ASSESSMENT: "Error updating anxiety assessment",
			ERROR_DELETING_ASSESSMENT: "Error deleting anxiety assessment",
			INVALID_DATA: "Invalid anxiety assessment data provided",
			EXISTING_ASSESSMENT: "Anxiety assessment already exists for this date",
			USER_NOT_FOUND: "User not found",
			INVALID_USER_ID: "Invalid user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_ANXIETY_LEVEL: "Invalid anxiety level value",
			INVALID_DIFFICULTY_LEVEL: "Invalid difficulty level value",
			ASSESSMENT_DATE_REQUIRED: "Assessment date is required",
			INVALID_ASSESSMENT_DATE: "Invalid assessment date format",
			GAD7_RESPONSES_REQUIRED: "All GAD-7 responses are required",
			INVALID_GAD7_RESPONSE: "Invalid GAD-7 response value",
			COOLDOWN_ACTIVE: "Assessment cooldown period is still active",
			ASSESSMENT_TOO_SOON: "Cannot create new assessment - cooldown period not yet expired",
			COOLDOWN_UPDATE_PERMISSION_DENIED: "Insufficient permissions to modify cooldown status",
			INVALID_COOLDOWN_VALUE: "Invalid cooldownActive value - must be true or false",
		},
		STRESS: {
			NOT_FOUND: "Stress assessment not found",
			INVALID_ID: "Invalid stress assessment ID",
			MISSING_ID: "Missing stress assessment ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ASSESSMENT: "Error getting stress assessment",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update stress assessment",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ASSESSMENT: "Error updating stress assessment",
			ERROR_DELETING_ASSESSMENT: "Error deleting stress assessment",
			INVALID_DATA: "Invalid stress assessment data provided",
			EXISTING_ASSESSMENT: "Stress assessment already exists for this date",
			USER_NOT_FOUND: "User not found",
			INVALID_USER_ID: "Invalid user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_STRESS_FREQUENCY: "Invalid stress frequency value",
			ASSESSMENT_DATE_REQUIRED: "Assessment date is required",
			INVALID_ASSESSMENT_DATE: "Invalid assessment date format",
			PSS10_RESPONSES_REQUIRED: "All PSS-10 responses are required",
			INVALID_PSS10_RESPONSE: "Invalid PSS-10 response value",
			COOLDOWN_ACTIVE: "Assessment cooldown period is still active",
			ASSESSMENT_TOO_SOON: "Cannot create new assessment - cooldown period not yet expired",
			COOLDOWN_UPDATE_PERMISSION_DENIED: "Insufficient permissions to modify cooldown status",
			INVALID_COOLDOWN_VALUE: "Invalid cooldownActive value - must be true or false",
		},
		DEPRESSION: {
			NOT_FOUND: "Depression assessment not found",
			INVALID_ID: "Invalid depression assessment ID",
			MISSING_ID: "Missing depression assessment ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ASSESSMENT: "Error getting depression assessment",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update depression assessment",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ASSESSMENT: "Error updating depression assessment",
			ERROR_DELETING_ASSESSMENT: "Error deleting depression assessment",
			INVALID_DATA: "Invalid depression assessment data provided",
			EXISTING_ASSESSMENT: "Depression assessment already exists for this date",
			USER_NOT_FOUND: "User not found",
			INVALID_USER_ID: "Invalid user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_DEPRESSION_FREQUENCY: "Invalid depression frequency value",
			INVALID_DIFFICULTY_LEVEL: "Invalid difficulty level value",
			ASSESSMENT_DATE_REQUIRED: "Assessment date is required",
			INVALID_ASSESSMENT_DATE: "Invalid assessment date format",
			PHQ9_RESPONSES_REQUIRED: "All PHQ-9 responses are required",
			INVALID_PHQ9_RESPONSE: "Invalid PHQ-9 response value",
			COOLDOWN_ACTIVE: "Assessment cooldown period is still active",
			ASSESSMENT_TOO_SOON: "Cannot create new assessment - cooldown period not yet expired",
			COOLDOWN_UPDATE_PERMISSION_DENIED: "Insufficient permissions to modify cooldown status",
			INVALID_COOLDOWN_VALUE: "Invalid cooldownActive value - must be true or false",
			SUICIDAL_IDEATION_DETECTED:
				"Suicidal ideation detected - immediate intervention required",
		},
		SUICIDE: {
			NOT_FOUND: "Suicide assessment not found",
			INVALID_ID: "Invalid suicide assessment ID",
			MISSING_ID: "Missing suicide assessment ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_ASSESSMENT: "Error getting suicide assessment",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update suicide assessment",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_ASSESSMENT: "Error updating suicide assessment",
			ERROR_DELETING_ASSESSMENT: "Error deleting suicide assessment",
			INVALID_DATA: "Invalid suicide assessment data provided",
			EXISTING_ASSESSMENT: "Suicide assessment already exists for this date",
			USER_NOT_FOUND: "User not found",
			INVALID_USER_ID: "Invalid user ID",
			USER_ID_REQUIRED: "User ID is required",
			INVALID_SUICIDE_RESPONSE: "Invalid suicide response value",
			INVALID_RISK_LEVEL: "Invalid risk level value",
			INVALID_BEHAVIOR_TIMEFRAME: "Invalid behavior timeframe value",
			ASSESSMENT_DATE_REQUIRED: "Assessment date is required",
			INVALID_ASSESSMENT_DATE: "Invalid assessment date format",
			CSSRS_RESPONSES_REQUIRED: "CSSRS basic responses are required",
			INVALID_CSSRS_RESPONSE: "Invalid CSSRS response value",
			IMMEDIATE_INTERVENTION_REQUIRED:
				"Immediate intervention required - high suicide risk detected",
			CRISIS_RESPONSE_ACTIVATED: "Crisis response protocols have been activated",
		},
		RETAKE_REQUEST: {
			NOT_FOUND: "Retake request not found",
			INVALID_ID: "Invalid retake request ID",
			MISSING_ID: "Missing retake request ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_REQUEST: "Error getting retake request",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update retake request",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_REQUEST: "Error updating retake request",
			ERROR_DELETING_REQUEST: "Error deleting retake request",
			INVALID_DATA: "Invalid retake request data provided",
			USER_NOT_FOUND: "User not found",
			INVALID_USER_ID: "Invalid user ID",
			USER_ID_REQUIRED: "User ID is required",
			ASSESSMENT_TYPE_REQUIRED: "Assessment type is required",
			INVALID_ASSESSMENT_TYPE: "Invalid assessment type",
			REASON_REQUIRED: "Reason is required",
			INVALID_REASON: "Reason must be a non-empty string",
			STATUS_REQUIRED: "Status is required",
			INVALID_STATUS: "Invalid status value",
			EXISTING_PENDING_REQUEST:
				"You already have a pending retake request for this assessment type",
			INVALID_REVIEWER_ID: "Invalid reviewer ID",
			REVIEWER_COMMENTS_REQUIRED: "Reviewer comments are required when rejecting a request",
			PERMISSION_DENIED: "Insufficient permissions to perform this action",
			CANNOT_REVIEW_OWN_REQUEST: "Cannot review your own retake request",
			REQUEST_ALREADY_REVIEWED: "This retake request has already been reviewed",
			COOLDOWN_DEACTIVATION_FAILED: "Failed to deactivate assessment cooldown",
		},
		MESSAGE: {
			NOT_FOUND: "Message not found",
			INVALID_ID: "Invalid message ID",
			MISSING_ID: "Missing message ID",
			INVALID_POPULATE: "Invalid populate parameter",
			POPULATE_MUST_BE_STRING: "Populate parameter must be a comma-separated string",
			INTERNAL_SERVER_ERROR: "Internal server error",
			ERROR_GETTING_MESSAGE: "Error getting message",
			INVALID_PAGE: "Invalid page number",
			INVALID_LIMIT: "Invalid limit number",
			INVALID_ORDER: "Invalid order parameter",
			ORDER_MUST_BE_ASC_OR_DESC: "Order must be either 'asc' or 'desc'",
			INVALID_SELECT: "Invalid select parameter",
			SELECT_MUST_BE_STRING: "Select parameter must be a comma-separated string",
			INVALID_SORT: "Invalid sort parameter",
			SORT_MUST_BE_STRING: "Sort parameter must be a valid JSON string or field name",
			NO_UPDATE_FIELDS: "No update fields provided",
			UPDATE_FAILED: "Failed to update message",
			AT_LEAST_ONE_FIELD_REQUIRED: "At least one field is required for update",
			ERROR_UPDATING_MESSAGE: "Error updating message",
			ERROR_DELETING_MESSAGE: "Error deleting message",
			INVALID_DATA: "Invalid message data provided",
			EXISTING_MESSAGE: "Message already exists",
			INVALID_TITLE: "Invalid message title",
			TITLE_REQUIRED: "Message title is required",
			INVALID_CONTENT: "Invalid message content",
			CONTENT_REQUIRED: "Message content is required",
			INVALID_ATTACHEMENT: "Invalid attachment value",
		},
	},

	SUCCESS: {
		USER: {
			RETRIEVED: "User retrieved",
			DELETED: "User deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "User updated",
			CREATED: "User created",
			LOGGED_IN: "User logged in",
			GETTING_USER_BY_ID: "Getting user by ID",
			GETTING_ALL_USERS: "Getting all users",
		},
		PERSON: {
			RETRIEVED: "Person retrieved",
			DELETED: "Person deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "Person updated",
			CREATED: "Person created",
			LOGGED_IN: "Person logged in",
			GETTING_USER_BY_ID: "Getting person by ID",
			GETTING_ALL_USERS: "Getting all persons",
		},
		STUDENT: {
			RETRIEVED: "Student retrieved",
			DELETED: "Student deleted",
			SOFT_DELETING: "Soft deleting user",
			UPDATE: "Student updated",
			CREATED: "Student created",
			LOGGED_IN: "Student logged in",
			GETTING_USER_BY_ID: "Getting student by ID",
			GETTING_ALL_USERS: "Getting all students",
		},
		ANNOUNCEMENT: {
			RETRIEVED: "Announcement retrieved",
			DELETED: "Announcement deleted",
			SOFT_DELETING: "Soft deleting announcement",
			UPDATE: "Announcement updated",
			CREATED: "Announcement created",
			GETTING_BY_ID: "Getting announcement by ID",
			GETTING_ALL: "Getting all announcements",
		},
		CONSENT: {
			RETRIEVED: "Consent retrieved",
			DELETED: "Consent deleted",
			SOFT_DELETING: "Soft deleting consent",
			UPDATE: "Consent updated",
			CREATED: "Consent created",
			GETTING_BY_ID: "Getting consent by ID",
			GETTING_ALL: "Getting all consents",
		},
		LOGS: {
			RETRIEVED: "Log retrieved",
			DELETED: "Log deleted",
			SOFT_DELETING: "Soft deleting log",
			UPDATE: "Log updated",
			CREATED: "Log created",
			GETTING_BY_ID: "Getting log by ID",
			GETTING_ALL: "Getting all logs",
			MARKED_AS_READ: "Log marked as read",
			MARKED_AS_UNREAD: "Log marked as unread",
		},
		ANXIETY: {
			RETRIEVED: "Anxiety assessment retrieved",
			DELETED: "Anxiety assessment deleted",
			SOFT_DELETING: "Soft deleting anxiety assessment",
			UPDATE: "Anxiety assessment updated",
			CREATED: "Anxiety assessment created",
			GETTING_BY_ID: "Getting anxiety assessment by ID",
			GETTING_ALL: "Getting all anxiety assessments",
			SCORE_CALCULATED: "GAD-7 score calculated successfully",
			SEVERITY_DETERMINED: "Anxiety severity level determined",
			COOLDOWN_CHECKED: "Assessment cooldown period checked",
			COOLDOWN_EXPIRED: "Assessment cooldown period has expired",
			COOLDOWN_UPDATED: "Assessment cooldown status updated successfully",
			COOLDOWN_DEACTIVATED_BY_ADMIN: "Cooldown manually deactivated by administrator",
			COOLDOWN_ACTIVATED_BY_ADMIN: "Cooldown manually activated by administrator",
		},
		STRESS: {
			RETRIEVED: "Stress assessment retrieved",
			DELETED: "Stress assessment deleted",
			SOFT_DELETING: "Soft deleting stress assessment",
			UPDATE: "Stress assessment updated",
			CREATED: "Stress assessment created",
			GETTING_BY_ID: "Getting stress assessment by ID",
			GETTING_ALL: "Getting all stress assessments",
			SCORE_CALCULATED: "PSS-10 score calculated successfully",
			SEVERITY_DETERMINED: "Stress severity level determined",
			COOLDOWN_CHECKED: "Assessment cooldown period checked",
			COOLDOWN_EXPIRED: "Assessment cooldown period has expired",
			COOLDOWN_UPDATED: "Assessment cooldown status updated successfully",
			COOLDOWN_DEACTIVATED_BY_ADMIN: "Cooldown manually deactivated by administrator",
			COOLDOWN_ACTIVATED_BY_ADMIN: "Cooldown manually activated by administrator",
		},
		DEPRESSION: {
			RETRIEVED: "Depression assessment retrieved",
			DELETED: "Depression assessment deleted",
			SOFT_DELETING: "Soft deleting depression assessment",
			UPDATE: "Depression assessment updated",
			CREATED: "Depression assessment created",
			GETTING_BY_ID: "Getting depression assessment by ID",
			GETTING_ALL: "Getting all depression assessments",
			SCORE_CALCULATED: "PHQ-9 score calculated successfully",
			SEVERITY_DETERMINED: "Depression severity level determined",
			COOLDOWN_CHECKED: "Assessment cooldown period checked",
			COOLDOWN_EXPIRED: "Assessment cooldown period has expired",
			COOLDOWN_UPDATED: "Assessment cooldown status updated successfully",
			COOLDOWN_DEACTIVATED_BY_ADMIN: "Cooldown manually deactivated by administrator",
			COOLDOWN_ACTIVATED_BY_ADMIN: "Cooldown manually activated by administrator",
			SUICIDAL_IDEATION_FLAGGED: "Suicidal ideation flagged for immediate attention",
		},
		SUICIDE: {
			RETRIEVED: "Suicide assessment retrieved",
			DELETED: "Suicide assessment deleted",
			SOFT_DELETING: "Soft deleting suicide assessment",
			UPDATE: "Suicide assessment updated",
			CREATED: "Suicide assessment created",
			GETTING_BY_ID: "Getting suicide assessment by ID",
			GETTING_ALL: "Getting all suicide assessments",
			RISK_ASSESSED: "Suicide risk level assessed successfully",
			INTERVENTION_STATUS_DETERMINED: "Intervention status determined",
			CSSRS_COMPLETED: "CSSRS assessment completed successfully",
			CRISIS_PROTOCOL_INITIATED: "Crisis intervention protocol initiated",
			SAFETY_PLAN_RECOMMENDED: "Safety plan creation recommended",
		},
		RETAKE_REQUEST: {
			RETRIEVED: "Retake request retrieved",
			DELETED: "Retake request deleted",
			SOFT_DELETING: "Soft deleting retake request",
			UPDATE: "Retake request updated",
			CREATED: "Retake request created",
			GETTING_BY_ID: "Getting retake request by ID",
			GETTING_ALL: "Getting all retake requests",
			REQUEST_SUBMITTED: "Retake request submitted successfully",
			REQUEST_APPROVED: "Retake request approved successfully",
			REQUEST_REJECTED: "Retake request rejected",
			COOLDOWN_DEACTIVATED: "Assessment cooldown deactivated successfully",
			COOLDOWN_MAINTAINED: "Assessment cooldown maintained as requested",
			REVIEW_COMPLETED: "Retake request review completed",
			STATUS_UPDATED: "Retake request status updated successfully",
		},
		MESSAGE: {
			RETRIEVED: "Message retrieved",
			DELETED: "Message deleted",
			SOFT_DELETING: "Soft deleting message",
			UPDATE: "Message updated",
			CREATED: "Message created",
			GETTING_BY_ID: "Getting message by ID",
			GETTING_ALL: "Getting all messages",
		},
	},
};
